-- MySQL Script generated by MySQL Workbench
-- Wed May 31 11:26:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webshop` ;

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8 ;
USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`user` ;

CREATE TABLE IF NOT EXISTS `webshop`.`user` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`categorie` ;

CREATE TABLE IF NOT EXISTS `webshop`.`categorie` (
  `categroie_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categroie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`subcategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`subcategorie` ;

CREATE TABLE IF NOT EXISTS `webshop`.`subcategorie` (
  `subcategorie_id` INT NOT NULL,
  `categroie_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`subcategorie_id`),
  INDEX `fk_subcategorie_categorie1_idx` (`categroie_id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategorie_categorie1`
    FOREIGN KEY (`categroie_id`)
    REFERENCES `webshop`.`categorie` (`categroie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`product` ;

CREATE TABLE IF NOT EXISTS `webshop`.`product` (
  `product_id` INT NOT NULL,
  `subcategorie_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_subcategorie1_idx` (`subcategorie_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_subcategorie1`
    FOREIGN KEY (`subcategorie_id`)
    REFERENCES `webshop`.`subcategorie` (`subcategorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`cart` ;

CREATE TABLE IF NOT EXISTS `webshop`.`cart` (
  `cart_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `fk_cart_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `webshop`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`order` ;

CREATE TABLE IF NOT EXISTS `webshop`.`order` (
  `order_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `purchase_date` DATE NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `webshop`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`cart_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`cart_product` ;

CREATE TABLE IF NOT EXISTS `webshop`.`cart_product` (
  `cart_product_id` INT NOT NULL,
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`cart_product_id`),
  INDEX `fk_cart_product_cart1_idx` (`cart_id` ASC) VISIBLE,
  INDEX `fk_cart_product_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_product_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `webshop`.`cart` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `webshop`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`order_product` ;

CREATE TABLE IF NOT EXISTS `webshop`.`order_product` (
  `order_product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`order_product_id`),
  INDEX `fk_order_product_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_product_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `webshop`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `webshop`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
